# registry.cn-hongkong.aliyuncs.com/lensfa/easy-forward:latest

# 使用官方的Go镜像作为构建环境
FROM golang:1.21-bullseye as builder

# 设置工作目录
WORKDIR /app

# 复制源码到容器中
COPY . .

# 下载所有依赖
RUN apt update &&  \
    apt install build-essential libpcap-dev -y

RUN go install

# 构建应用程序
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ef

FROM alpine:latest

WORKDIR /app

# 从构建阶段复制编译好的应用程序
COPY --from=builder /app/ef /app/ef

# 暴露端口
EXPOSE 8888

RUN set -ex \
	&& apk add --no-cache tzdata \
    && chmod +x ef

VOLUME /app/config
ENV TZ=Asia/Shanghai
CMD [ "/app/easy-forward", "-c", "/app/config/config.yaml"]